
/*
Auto-generated by CVXPYgen on June 03, 2025 at 13:49:14.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_target_position(0, 0.00000000000000000000);
  cpg_update_initial_position(0, 100.00000000000000000000);
  cpg_update_initial_vel(0, 0.00000000000000000000);
  cpg_update_log_mass(10.77593088463000725596);
  cpg_update_max_vel(1000.00000000000000000000);
  cpg_update_sin_glide_slope(0.49999999999999994449);
  cpg_update_max_angle(0.99619469809174554520);
  cpg_update_z0(0, 10.77593088463000725596);
  cpg_update_min_exp_z0(0, 0.18166767801287000972);
  cpg_update_max_exp_z0(0, 0.07085039442501929463);
  cpg_update_dt(0.50000000000000000000);
  cpg_update_dt_squared(0.25000000000000000000);
  cpg_update_gravity_dt_squared(0, 0.00000000000000000000);
  cpg_update_gravity_dt(0, 0.00000000000000000000);
  cpg_update_fuel_consumption_dt(0.00018048128342245989);
  cpg_update_target_velocity(0, 0.00000000000000000000);
  cpg_update_log_dry_mass(9.70783756553084131724);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<360; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }
  for(i=0; i<60; i++) {
    printf("z[%d] = %f\n", i, CPG_Result.prim->z[i]);
  }
  for(i=0; i<180; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<60; i++) {
    printf("s[%d] = %f\n", i, CPG_Result.prim->s[i]);
  }

  // Print dual solution
  for(i=0; i<3; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", CPG_Result.dual->d2);
  printf("d3 = %f\n", CPG_Result.dual->d3);
  printf("d4 = %f\n", CPG_Result.dual->d4);
  printf("d5 = %f\n", CPG_Result.dual->d5);
  printf("d6 = %f\n", CPG_Result.dual->d6);
  printf("d7 = %f\n", CPG_Result.dual->d7);
  printf("d8 = %f\n", CPG_Result.dual->d8);
  for(i=0; i<3; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<3; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  printf("d11 = %f\n", CPG_Result.dual->d11);
  printf("d12 = %f\n", CPG_Result.dual->d12);
  printf("d13 = %f\n", CPG_Result.dual->d13);
  printf("d14 = %f\n", CPG_Result.dual->d14);
  printf("d15 = %f\n", CPG_Result.dual->d15);
  printf("d16 = %f\n", CPG_Result.dual->d16);
  printf("d17 = %f\n", CPG_Result.dual->d17);
  for(i=0; i<3; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<3; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  printf("d20 = %f\n", CPG_Result.dual->d20);
  printf("d21 = %f\n", CPG_Result.dual->d21);
  printf("d22 = %f\n", CPG_Result.dual->d22);
  printf("d23 = %f\n", CPG_Result.dual->d23);
  printf("d24 = %f\n", CPG_Result.dual->d24);
  printf("d25 = %f\n", CPG_Result.dual->d25);
  printf("d26 = %f\n", CPG_Result.dual->d26);
  for(i=0; i<3; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<3; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  printf("d29 = %f\n", CPG_Result.dual->d29);
  printf("d30 = %f\n", CPG_Result.dual->d30);
  printf("d31 = %f\n", CPG_Result.dual->d31);
  printf("d32 = %f\n", CPG_Result.dual->d32);
  printf("d33 = %f\n", CPG_Result.dual->d33);
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  for(i=0; i<3; i++) {
    printf("d36[%d] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  for(i=0; i<3; i++) {
    printf("d37[%d] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  for(i=0; i<3; i++) {
    printf("d45[%d] = %f\n", i, CPG_Result.dual->d45[i]);
  }
  for(i=0; i<3; i++) {
    printf("d46[%d] = %f\n", i, CPG_Result.dual->d46[i]);
  }
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  for(i=0; i<3; i++) {
    printf("d54[%d] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  for(i=0; i<3; i++) {
    printf("d55[%d] = %f\n", i, CPG_Result.dual->d55[i]);
  }
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  for(i=0; i<3; i++) {
    printf("d63[%d] = %f\n", i, CPG_Result.dual->d63[i]);
  }
  for(i=0; i<3; i++) {
    printf("d64[%d] = %f\n", i, CPG_Result.dual->d64[i]);
  }
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  for(i=0; i<3; i++) {
    printf("d72[%d] = %f\n", i, CPG_Result.dual->d72[i]);
  }
  for(i=0; i<3; i++) {
    printf("d73[%d] = %f\n", i, CPG_Result.dual->d73[i]);
  }
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  printf("d77 = %f\n", CPG_Result.dual->d77);
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  for(i=0; i<3; i++) {
    printf("d81[%d] = %f\n", i, CPG_Result.dual->d81[i]);
  }
  for(i=0; i<3; i++) {
    printf("d82[%d] = %f\n", i, CPG_Result.dual->d82[i]);
  }
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  printf("d86 = %f\n", CPG_Result.dual->d86);
  printf("d87 = %f\n", CPG_Result.dual->d87);
  printf("d88 = %f\n", CPG_Result.dual->d88);
  printf("d89 = %f\n", CPG_Result.dual->d89);
  for(i=0; i<3; i++) {
    printf("d90[%d] = %f\n", i, CPG_Result.dual->d90[i]);
  }
  for(i=0; i<3; i++) {
    printf("d91[%d] = %f\n", i, CPG_Result.dual->d91[i]);
  }
  printf("d92 = %f\n", CPG_Result.dual->d92);
  printf("d93 = %f\n", CPG_Result.dual->d93);
  printf("d94 = %f\n", CPG_Result.dual->d94);
  printf("d95 = %f\n", CPG_Result.dual->d95);
  printf("d96 = %f\n", CPG_Result.dual->d96);
  printf("d97 = %f\n", CPG_Result.dual->d97);
  printf("d98 = %f\n", CPG_Result.dual->d98);
  for(i=0; i<3; i++) {
    printf("d99[%d] = %f\n", i, CPG_Result.dual->d99[i]);
  }
  for(i=0; i<3; i++) {
    printf("d100[%d] = %f\n", i, CPG_Result.dual->d100[i]);
  }
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  for(i=0; i<3; i++) {
    printf("d108[%d] = %f\n", i, CPG_Result.dual->d108[i]);
  }
  for(i=0; i<3; i++) {
    printf("d109[%d] = %f\n", i, CPG_Result.dual->d109[i]);
  }
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  for(i=0; i<3; i++) {
    printf("d117[%d] = %f\n", i, CPG_Result.dual->d117[i]);
  }
  for(i=0; i<3; i++) {
    printf("d118[%d] = %f\n", i, CPG_Result.dual->d118[i]);
  }
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  printf("d122 = %f\n", CPG_Result.dual->d122);
  printf("d123 = %f\n", CPG_Result.dual->d123);
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  for(i=0; i<3; i++) {
    printf("d126[%d] = %f\n", i, CPG_Result.dual->d126[i]);
  }
  for(i=0; i<3; i++) {
    printf("d127[%d] = %f\n", i, CPG_Result.dual->d127[i]);
  }
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  printf("d131 = %f\n", CPG_Result.dual->d131);
  printf("d132 = %f\n", CPG_Result.dual->d132);
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  for(i=0; i<3; i++) {
    printf("d135[%d] = %f\n", i, CPG_Result.dual->d135[i]);
  }
  for(i=0; i<3; i++) {
    printf("d136[%d] = %f\n", i, CPG_Result.dual->d136[i]);
  }
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  printf("d140 = %f\n", CPG_Result.dual->d140);
  printf("d141 = %f\n", CPG_Result.dual->d141);
  printf("d142 = %f\n", CPG_Result.dual->d142);
  printf("d143 = %f\n", CPG_Result.dual->d143);
  for(i=0; i<3; i++) {
    printf("d144[%d] = %f\n", i, CPG_Result.dual->d144[i]);
  }
  for(i=0; i<3; i++) {
    printf("d145[%d] = %f\n", i, CPG_Result.dual->d145[i]);
  }
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  printf("d149 = %f\n", CPG_Result.dual->d149);
  printf("d150 = %f\n", CPG_Result.dual->d150);
  printf("d151 = %f\n", CPG_Result.dual->d151);
  printf("d152 = %f\n", CPG_Result.dual->d152);
  for(i=0; i<3; i++) {
    printf("d153[%d] = %f\n", i, CPG_Result.dual->d153[i]);
  }
  for(i=0; i<3; i++) {
    printf("d154[%d] = %f\n", i, CPG_Result.dual->d154[i]);
  }
  printf("d155 = %f\n", CPG_Result.dual->d155);
  printf("d156 = %f\n", CPG_Result.dual->d156);
  printf("d157 = %f\n", CPG_Result.dual->d157);
  printf("d158 = %f\n", CPG_Result.dual->d158);
  printf("d159 = %f\n", CPG_Result.dual->d159);
  printf("d160 = %f\n", CPG_Result.dual->d160);
  printf("d161 = %f\n", CPG_Result.dual->d161);
  for(i=0; i<3; i++) {
    printf("d162[%d] = %f\n", i, CPG_Result.dual->d162[i]);
  }
  for(i=0; i<3; i++) {
    printf("d163[%d] = %f\n", i, CPG_Result.dual->d163[i]);
  }
  printf("d164 = %f\n", CPG_Result.dual->d164);
  printf("d165 = %f\n", CPG_Result.dual->d165);
  printf("d166 = %f\n", CPG_Result.dual->d166);
  printf("d167 = %f\n", CPG_Result.dual->d167);
  printf("d168 = %f\n", CPG_Result.dual->d168);
  printf("d169 = %f\n", CPG_Result.dual->d169);
  printf("d170 = %f\n", CPG_Result.dual->d170);
  for(i=0; i<3; i++) {
    printf("d171[%d] = %f\n", i, CPG_Result.dual->d171[i]);
  }
  for(i=0; i<3; i++) {
    printf("d172[%d] = %f\n", i, CPG_Result.dual->d172[i]);
  }
  printf("d173 = %f\n", CPG_Result.dual->d173);
  printf("d174 = %f\n", CPG_Result.dual->d174);
  printf("d175 = %f\n", CPG_Result.dual->d175);
  printf("d176 = %f\n", CPG_Result.dual->d176);
  printf("d177 = %f\n", CPG_Result.dual->d177);
  printf("d178 = %f\n", CPG_Result.dual->d178);
  printf("d179 = %f\n", CPG_Result.dual->d179);
  for(i=0; i<3; i++) {
    printf("d180[%d] = %f\n", i, CPG_Result.dual->d180[i]);
  }
  for(i=0; i<3; i++) {
    printf("d181[%d] = %f\n", i, CPG_Result.dual->d181[i]);
  }
  printf("d182 = %f\n", CPG_Result.dual->d182);
  printf("d183 = %f\n", CPG_Result.dual->d183);
  printf("d184 = %f\n", CPG_Result.dual->d184);
  printf("d185 = %f\n", CPG_Result.dual->d185);
  printf("d186 = %f\n", CPG_Result.dual->d186);
  printf("d187 = %f\n", CPG_Result.dual->d187);
  printf("d188 = %f\n", CPG_Result.dual->d188);
  for(i=0; i<3; i++) {
    printf("d189[%d] = %f\n", i, CPG_Result.dual->d189[i]);
  }
  for(i=0; i<3; i++) {
    printf("d190[%d] = %f\n", i, CPG_Result.dual->d190[i]);
  }
  printf("d191 = %f\n", CPG_Result.dual->d191);
  printf("d192 = %f\n", CPG_Result.dual->d192);
  printf("d193 = %f\n", CPG_Result.dual->d193);
  printf("d194 = %f\n", CPG_Result.dual->d194);
  printf("d195 = %f\n", CPG_Result.dual->d195);
  printf("d196 = %f\n", CPG_Result.dual->d196);
  printf("d197 = %f\n", CPG_Result.dual->d197);
  for(i=0; i<3; i++) {
    printf("d198[%d] = %f\n", i, CPG_Result.dual->d198[i]);
  }
  for(i=0; i<3; i++) {
    printf("d199[%d] = %f\n", i, CPG_Result.dual->d199[i]);
  }
  printf("d200 = %f\n", CPG_Result.dual->d200);
  printf("d201 = %f\n", CPG_Result.dual->d201);
  printf("d202 = %f\n", CPG_Result.dual->d202);
  printf("d203 = %f\n", CPG_Result.dual->d203);
  printf("d204 = %f\n", CPG_Result.dual->d204);
  printf("d205 = %f\n", CPG_Result.dual->d205);
  printf("d206 = %f\n", CPG_Result.dual->d206);
  for(i=0; i<3; i++) {
    printf("d207[%d] = %f\n", i, CPG_Result.dual->d207[i]);
  }
  for(i=0; i<3; i++) {
    printf("d208[%d] = %f\n", i, CPG_Result.dual->d208[i]);
  }
  printf("d209 = %f\n", CPG_Result.dual->d209);
  printf("d210 = %f\n", CPG_Result.dual->d210);
  printf("d211 = %f\n", CPG_Result.dual->d211);
  printf("d212 = %f\n", CPG_Result.dual->d212);
  printf("d213 = %f\n", CPG_Result.dual->d213);
  printf("d214 = %f\n", CPG_Result.dual->d214);
  printf("d215 = %f\n", CPG_Result.dual->d215);
  for(i=0; i<3; i++) {
    printf("d216[%d] = %f\n", i, CPG_Result.dual->d216[i]);
  }
  for(i=0; i<3; i++) {
    printf("d217[%d] = %f\n", i, CPG_Result.dual->d217[i]);
  }
  printf("d218 = %f\n", CPG_Result.dual->d218);
  printf("d219 = %f\n", CPG_Result.dual->d219);
  printf("d220 = %f\n", CPG_Result.dual->d220);
  printf("d221 = %f\n", CPG_Result.dual->d221);
  printf("d222 = %f\n", CPG_Result.dual->d222);
  printf("d223 = %f\n", CPG_Result.dual->d223);
  printf("d224 = %f\n", CPG_Result.dual->d224);
  for(i=0; i<3; i++) {
    printf("d225[%d] = %f\n", i, CPG_Result.dual->d225[i]);
  }
  for(i=0; i<3; i++) {
    printf("d226[%d] = %f\n", i, CPG_Result.dual->d226[i]);
  }
  printf("d227 = %f\n", CPG_Result.dual->d227);
  printf("d228 = %f\n", CPG_Result.dual->d228);
  printf("d229 = %f\n", CPG_Result.dual->d229);
  printf("d230 = %f\n", CPG_Result.dual->d230);
  printf("d231 = %f\n", CPG_Result.dual->d231);
  printf("d232 = %f\n", CPG_Result.dual->d232);
  printf("d233 = %f\n", CPG_Result.dual->d233);
  for(i=0; i<3; i++) {
    printf("d234[%d] = %f\n", i, CPG_Result.dual->d234[i]);
  }
  for(i=0; i<3; i++) {
    printf("d235[%d] = %f\n", i, CPG_Result.dual->d235[i]);
  }
  printf("d236 = %f\n", CPG_Result.dual->d236);
  printf("d237 = %f\n", CPG_Result.dual->d237);
  printf("d238 = %f\n", CPG_Result.dual->d238);
  printf("d239 = %f\n", CPG_Result.dual->d239);
  printf("d240 = %f\n", CPG_Result.dual->d240);
  printf("d241 = %f\n", CPG_Result.dual->d241);
  printf("d242 = %f\n", CPG_Result.dual->d242);
  for(i=0; i<3; i++) {
    printf("d243[%d] = %f\n", i, CPG_Result.dual->d243[i]);
  }
  for(i=0; i<3; i++) {
    printf("d244[%d] = %f\n", i, CPG_Result.dual->d244[i]);
  }
  printf("d245 = %f\n", CPG_Result.dual->d245);
  printf("d246 = %f\n", CPG_Result.dual->d246);
  printf("d247 = %f\n", CPG_Result.dual->d247);
  printf("d248 = %f\n", CPG_Result.dual->d248);
  printf("d249 = %f\n", CPG_Result.dual->d249);
  printf("d250 = %f\n", CPG_Result.dual->d250);
  printf("d251 = %f\n", CPG_Result.dual->d251);
  for(i=0; i<3; i++) {
    printf("d252[%d] = %f\n", i, CPG_Result.dual->d252[i]);
  }
  for(i=0; i<3; i++) {
    printf("d253[%d] = %f\n", i, CPG_Result.dual->d253[i]);
  }
  printf("d254 = %f\n", CPG_Result.dual->d254);
  printf("d255 = %f\n", CPG_Result.dual->d255);
  printf("d256 = %f\n", CPG_Result.dual->d256);
  printf("d257 = %f\n", CPG_Result.dual->d257);
  printf("d258 = %f\n", CPG_Result.dual->d258);
  printf("d259 = %f\n", CPG_Result.dual->d259);
  printf("d260 = %f\n", CPG_Result.dual->d260);
  for(i=0; i<3; i++) {
    printf("d261[%d] = %f\n", i, CPG_Result.dual->d261[i]);
  }
  for(i=0; i<3; i++) {
    printf("d262[%d] = %f\n", i, CPG_Result.dual->d262[i]);
  }
  printf("d263 = %f\n", CPG_Result.dual->d263);
  printf("d264 = %f\n", CPG_Result.dual->d264);
  printf("d265 = %f\n", CPG_Result.dual->d265);
  printf("d266 = %f\n", CPG_Result.dual->d266);
  printf("d267 = %f\n", CPG_Result.dual->d267);
  printf("d268 = %f\n", CPG_Result.dual->d268);
  printf("d269 = %f\n", CPG_Result.dual->d269);
  for(i=0; i<3; i++) {
    printf("d270[%d] = %f\n", i, CPG_Result.dual->d270[i]);
  }
  for(i=0; i<3; i++) {
    printf("d271[%d] = %f\n", i, CPG_Result.dual->d271[i]);
  }
  printf("d272 = %f\n", CPG_Result.dual->d272);
  printf("d273 = %f\n", CPG_Result.dual->d273);
  printf("d274 = %f\n", CPG_Result.dual->d274);
  printf("d275 = %f\n", CPG_Result.dual->d275);
  printf("d276 = %f\n", CPG_Result.dual->d276);
  printf("d277 = %f\n", CPG_Result.dual->d277);
  printf("d278 = %f\n", CPG_Result.dual->d278);
  for(i=0; i<3; i++) {
    printf("d279[%d] = %f\n", i, CPG_Result.dual->d279[i]);
  }
  for(i=0; i<3; i++) {
    printf("d280[%d] = %f\n", i, CPG_Result.dual->d280[i]);
  }
  printf("d281 = %f\n", CPG_Result.dual->d281);
  printf("d282 = %f\n", CPG_Result.dual->d282);
  printf("d283 = %f\n", CPG_Result.dual->d283);
  printf("d284 = %f\n", CPG_Result.dual->d284);
  printf("d285 = %f\n", CPG_Result.dual->d285);
  printf("d286 = %f\n", CPG_Result.dual->d286);
  printf("d287 = %f\n", CPG_Result.dual->d287);
  for(i=0; i<3; i++) {
    printf("d288[%d] = %f\n", i, CPG_Result.dual->d288[i]);
  }
  for(i=0; i<3; i++) {
    printf("d289[%d] = %f\n", i, CPG_Result.dual->d289[i]);
  }
  printf("d290 = %f\n", CPG_Result.dual->d290);
  printf("d291 = %f\n", CPG_Result.dual->d291);
  printf("d292 = %f\n", CPG_Result.dual->d292);
  printf("d293 = %f\n", CPG_Result.dual->d293);
  printf("d294 = %f\n", CPG_Result.dual->d294);
  printf("d295 = %f\n", CPG_Result.dual->d295);
  printf("d296 = %f\n", CPG_Result.dual->d296);
  for(i=0; i<3; i++) {
    printf("d297[%d] = %f\n", i, CPG_Result.dual->d297[i]);
  }
  for(i=0; i<3; i++) {
    printf("d298[%d] = %f\n", i, CPG_Result.dual->d298[i]);
  }
  printf("d299 = %f\n", CPG_Result.dual->d299);
  printf("d300 = %f\n", CPG_Result.dual->d300);
  printf("d301 = %f\n", CPG_Result.dual->d301);
  printf("d302 = %f\n", CPG_Result.dual->d302);
  printf("d303 = %f\n", CPG_Result.dual->d303);
  printf("d304 = %f\n", CPG_Result.dual->d304);
  printf("d305 = %f\n", CPG_Result.dual->d305);
  for(i=0; i<3; i++) {
    printf("d306[%d] = %f\n", i, CPG_Result.dual->d306[i]);
  }
  for(i=0; i<3; i++) {
    printf("d307[%d] = %f\n", i, CPG_Result.dual->d307[i]);
  }
  printf("d308 = %f\n", CPG_Result.dual->d308);
  printf("d309 = %f\n", CPG_Result.dual->d309);
  printf("d310 = %f\n", CPG_Result.dual->d310);
  printf("d311 = %f\n", CPG_Result.dual->d311);
  printf("d312 = %f\n", CPG_Result.dual->d312);
  printf("d313 = %f\n", CPG_Result.dual->d313);
  printf("d314 = %f\n", CPG_Result.dual->d314);
  for(i=0; i<3; i++) {
    printf("d315[%d] = %f\n", i, CPG_Result.dual->d315[i]);
  }
  for(i=0; i<3; i++) {
    printf("d316[%d] = %f\n", i, CPG_Result.dual->d316[i]);
  }
  printf("d317 = %f\n", CPG_Result.dual->d317);
  printf("d318 = %f\n", CPG_Result.dual->d318);
  printf("d319 = %f\n", CPG_Result.dual->d319);
  printf("d320 = %f\n", CPG_Result.dual->d320);
  printf("d321 = %f\n", CPG_Result.dual->d321);
  printf("d322 = %f\n", CPG_Result.dual->d322);
  printf("d323 = %f\n", CPG_Result.dual->d323);
  for(i=0; i<3; i++) {
    printf("d324[%d] = %f\n", i, CPG_Result.dual->d324[i]);
  }
  for(i=0; i<3; i++) {
    printf("d325[%d] = %f\n", i, CPG_Result.dual->d325[i]);
  }
  printf("d326 = %f\n", CPG_Result.dual->d326);
  printf("d327 = %f\n", CPG_Result.dual->d327);
  printf("d328 = %f\n", CPG_Result.dual->d328);
  printf("d329 = %f\n", CPG_Result.dual->d329);
  printf("d330 = %f\n", CPG_Result.dual->d330);
  printf("d331 = %f\n", CPG_Result.dual->d331);
  printf("d332 = %f\n", CPG_Result.dual->d332);
  for(i=0; i<3; i++) {
    printf("d333[%d] = %f\n", i, CPG_Result.dual->d333[i]);
  }
  for(i=0; i<3; i++) {
    printf("d334[%d] = %f\n", i, CPG_Result.dual->d334[i]);
  }
  printf("d335 = %f\n", CPG_Result.dual->d335);
  printf("d336 = %f\n", CPG_Result.dual->d336);
  printf("d337 = %f\n", CPG_Result.dual->d337);
  printf("d338 = %f\n", CPG_Result.dual->d338);
  printf("d339 = %f\n", CPG_Result.dual->d339);
  printf("d340 = %f\n", CPG_Result.dual->d340);
  printf("d341 = %f\n", CPG_Result.dual->d341);
  for(i=0; i<3; i++) {
    printf("d342[%d] = %f\n", i, CPG_Result.dual->d342[i]);
  }
  for(i=0; i<3; i++) {
    printf("d343[%d] = %f\n", i, CPG_Result.dual->d343[i]);
  }
  printf("d344 = %f\n", CPG_Result.dual->d344);
  printf("d345 = %f\n", CPG_Result.dual->d345);
  printf("d346 = %f\n", CPG_Result.dual->d346);
  printf("d347 = %f\n", CPG_Result.dual->d347);
  printf("d348 = %f\n", CPG_Result.dual->d348);
  printf("d349 = %f\n", CPG_Result.dual->d349);
  printf("d350 = %f\n", CPG_Result.dual->d350);
  for(i=0; i<3; i++) {
    printf("d351[%d] = %f\n", i, CPG_Result.dual->d351[i]);
  }
  for(i=0; i<3; i++) {
    printf("d352[%d] = %f\n", i, CPG_Result.dual->d352[i]);
  }
  printf("d353 = %f\n", CPG_Result.dual->d353);
  printf("d354 = %f\n", CPG_Result.dual->d354);
  printf("d355 = %f\n", CPG_Result.dual->d355);
  printf("d356 = %f\n", CPG_Result.dual->d356);
  printf("d357 = %f\n", CPG_Result.dual->d357);
  printf("d358 = %f\n", CPG_Result.dual->d358);
  printf("d359 = %f\n", CPG_Result.dual->d359);
  for(i=0; i<3; i++) {
    printf("d360[%d] = %f\n", i, CPG_Result.dual->d360[i]);
  }
  for(i=0; i<3; i++) {
    printf("d361[%d] = %f\n", i, CPG_Result.dual->d361[i]);
  }
  printf("d362 = %f\n", CPG_Result.dual->d362);
  printf("d363 = %f\n", CPG_Result.dual->d363);
  printf("d364 = %f\n", CPG_Result.dual->d364);
  printf("d365 = %f\n", CPG_Result.dual->d365);
  printf("d366 = %f\n", CPG_Result.dual->d366);
  printf("d367 = %f\n", CPG_Result.dual->d367);
  printf("d368 = %f\n", CPG_Result.dual->d368);
  for(i=0; i<3; i++) {
    printf("d369[%d] = %f\n", i, CPG_Result.dual->d369[i]);
  }
  for(i=0; i<3; i++) {
    printf("d370[%d] = %f\n", i, CPG_Result.dual->d370[i]);
  }
  printf("d371 = %f\n", CPG_Result.dual->d371);
  printf("d372 = %f\n", CPG_Result.dual->d372);
  printf("d373 = %f\n", CPG_Result.dual->d373);
  printf("d374 = %f\n", CPG_Result.dual->d374);
  printf("d375 = %f\n", CPG_Result.dual->d375);
  printf("d376 = %f\n", CPG_Result.dual->d376);
  printf("d377 = %f\n", CPG_Result.dual->d377);
  for(i=0; i<3; i++) {
    printf("d378[%d] = %f\n", i, CPG_Result.dual->d378[i]);
  }
  for(i=0; i<3; i++) {
    printf("d379[%d] = %f\n", i, CPG_Result.dual->d379[i]);
  }
  printf("d380 = %f\n", CPG_Result.dual->d380);
  printf("d381 = %f\n", CPG_Result.dual->d381);
  printf("d382 = %f\n", CPG_Result.dual->d382);
  printf("d383 = %f\n", CPG_Result.dual->d383);
  printf("d384 = %f\n", CPG_Result.dual->d384);
  printf("d385 = %f\n", CPG_Result.dual->d385);
  printf("d386 = %f\n", CPG_Result.dual->d386);
  for(i=0; i<3; i++) {
    printf("d387[%d] = %f\n", i, CPG_Result.dual->d387[i]);
  }
  for(i=0; i<3; i++) {
    printf("d388[%d] = %f\n", i, CPG_Result.dual->d388[i]);
  }
  printf("d389 = %f\n", CPG_Result.dual->d389);
  printf("d390 = %f\n", CPG_Result.dual->d390);
  printf("d391 = %f\n", CPG_Result.dual->d391);
  printf("d392 = %f\n", CPG_Result.dual->d392);
  printf("d393 = %f\n", CPG_Result.dual->d393);
  printf("d394 = %f\n", CPG_Result.dual->d394);
  printf("d395 = %f\n", CPG_Result.dual->d395);
  for(i=0; i<3; i++) {
    printf("d396[%d] = %f\n", i, CPG_Result.dual->d396[i]);
  }
  for(i=0; i<3; i++) {
    printf("d397[%d] = %f\n", i, CPG_Result.dual->d397[i]);
  }
  printf("d398 = %f\n", CPG_Result.dual->d398);
  printf("d399 = %f\n", CPG_Result.dual->d399);
  printf("d400 = %f\n", CPG_Result.dual->d400);
  printf("d401 = %f\n", CPG_Result.dual->d401);
  printf("d402 = %f\n", CPG_Result.dual->d402);
  printf("d403 = %f\n", CPG_Result.dual->d403);
  printf("d404 = %f\n", CPG_Result.dual->d404);
  for(i=0; i<3; i++) {
    printf("d405[%d] = %f\n", i, CPG_Result.dual->d405[i]);
  }
  for(i=0; i<3; i++) {
    printf("d406[%d] = %f\n", i, CPG_Result.dual->d406[i]);
  }
  printf("d407 = %f\n", CPG_Result.dual->d407);
  printf("d408 = %f\n", CPG_Result.dual->d408);
  printf("d409 = %f\n", CPG_Result.dual->d409);
  printf("d410 = %f\n", CPG_Result.dual->d410);
  printf("d411 = %f\n", CPG_Result.dual->d411);
  printf("d412 = %f\n", CPG_Result.dual->d412);
  printf("d413 = %f\n", CPG_Result.dual->d413);
  for(i=0; i<3; i++) {
    printf("d414[%d] = %f\n", i, CPG_Result.dual->d414[i]);
  }
  for(i=0; i<3; i++) {
    printf("d415[%d] = %f\n", i, CPG_Result.dual->d415[i]);
  }
  printf("d416 = %f\n", CPG_Result.dual->d416);
  printf("d417 = %f\n", CPG_Result.dual->d417);
  printf("d418 = %f\n", CPG_Result.dual->d418);
  printf("d419 = %f\n", CPG_Result.dual->d419);
  printf("d420 = %f\n", CPG_Result.dual->d420);
  printf("d421 = %f\n", CPG_Result.dual->d421);
  printf("d422 = %f\n", CPG_Result.dual->d422);
  for(i=0; i<3; i++) {
    printf("d423[%d] = %f\n", i, CPG_Result.dual->d423[i]);
  }
  for(i=0; i<3; i++) {
    printf("d424[%d] = %f\n", i, CPG_Result.dual->d424[i]);
  }
  printf("d425 = %f\n", CPG_Result.dual->d425);
  printf("d426 = %f\n", CPG_Result.dual->d426);
  printf("d427 = %f\n", CPG_Result.dual->d427);
  printf("d428 = %f\n", CPG_Result.dual->d428);
  printf("d429 = %f\n", CPG_Result.dual->d429);
  printf("d430 = %f\n", CPG_Result.dual->d430);
  printf("d431 = %f\n", CPG_Result.dual->d431);
  for(i=0; i<3; i++) {
    printf("d432[%d] = %f\n", i, CPG_Result.dual->d432[i]);
  }
  for(i=0; i<3; i++) {
    printf("d433[%d] = %f\n", i, CPG_Result.dual->d433[i]);
  }
  printf("d434 = %f\n", CPG_Result.dual->d434);
  printf("d435 = %f\n", CPG_Result.dual->d435);
  printf("d436 = %f\n", CPG_Result.dual->d436);
  printf("d437 = %f\n", CPG_Result.dual->d437);
  printf("d438 = %f\n", CPG_Result.dual->d438);
  printf("d439 = %f\n", CPG_Result.dual->d439);
  printf("d440 = %f\n", CPG_Result.dual->d440);
  for(i=0; i<3; i++) {
    printf("d441[%d] = %f\n", i, CPG_Result.dual->d441[i]);
  }
  for(i=0; i<3; i++) {
    printf("d442[%d] = %f\n", i, CPG_Result.dual->d442[i]);
  }
  printf("d443 = %f\n", CPG_Result.dual->d443);
  printf("d444 = %f\n", CPG_Result.dual->d444);
  printf("d445 = %f\n", CPG_Result.dual->d445);
  printf("d446 = %f\n", CPG_Result.dual->d446);
  printf("d447 = %f\n", CPG_Result.dual->d447);
  printf("d448 = %f\n", CPG_Result.dual->d448);
  printf("d449 = %f\n", CPG_Result.dual->d449);
  for(i=0; i<3; i++) {
    printf("d450[%d] = %f\n", i, CPG_Result.dual->d450[i]);
  }
  for(i=0; i<3; i++) {
    printf("d451[%d] = %f\n", i, CPG_Result.dual->d451[i]);
  }
  printf("d452 = %f\n", CPG_Result.dual->d452);
  printf("d453 = %f\n", CPG_Result.dual->d453);
  printf("d454 = %f\n", CPG_Result.dual->d454);
  printf("d455 = %f\n", CPG_Result.dual->d455);
  printf("d456 = %f\n", CPG_Result.dual->d456);
  printf("d457 = %f\n", CPG_Result.dual->d457);
  printf("d458 = %f\n", CPG_Result.dual->d458);
  for(i=0; i<3; i++) {
    printf("d459[%d] = %f\n", i, CPG_Result.dual->d459[i]);
  }
  for(i=0; i<3; i++) {
    printf("d460[%d] = %f\n", i, CPG_Result.dual->d460[i]);
  }
  printf("d461 = %f\n", CPG_Result.dual->d461);
  printf("d462 = %f\n", CPG_Result.dual->d462);
  printf("d463 = %f\n", CPG_Result.dual->d463);
  printf("d464 = %f\n", CPG_Result.dual->d464);
  printf("d465 = %f\n", CPG_Result.dual->d465);
  printf("d466 = %f\n", CPG_Result.dual->d466);
  printf("d467 = %f\n", CPG_Result.dual->d467);
  for(i=0; i<3; i++) {
    printf("d468[%d] = %f\n", i, CPG_Result.dual->d468[i]);
  }
  for(i=0; i<3; i++) {
    printf("d469[%d] = %f\n", i, CPG_Result.dual->d469[i]);
  }
  printf("d470 = %f\n", CPG_Result.dual->d470);
  printf("d471 = %f\n", CPG_Result.dual->d471);
  printf("d472 = %f\n", CPG_Result.dual->d472);
  printf("d473 = %f\n", CPG_Result.dual->d473);
  printf("d474 = %f\n", CPG_Result.dual->d474);
  printf("d475 = %f\n", CPG_Result.dual->d475);
  printf("d476 = %f\n", CPG_Result.dual->d476);
  for(i=0; i<3; i++) {
    printf("d477[%d] = %f\n", i, CPG_Result.dual->d477[i]);
  }
  for(i=0; i<3; i++) {
    printf("d478[%d] = %f\n", i, CPG_Result.dual->d478[i]);
  }
  printf("d479 = %f\n", CPG_Result.dual->d479);
  printf("d480 = %f\n", CPG_Result.dual->d480);
  printf("d481 = %f\n", CPG_Result.dual->d481);
  printf("d482 = %f\n", CPG_Result.dual->d482);
  printf("d483 = %f\n", CPG_Result.dual->d483);
  printf("d484 = %f\n", CPG_Result.dual->d484);
  printf("d485 = %f\n", CPG_Result.dual->d485);
  for(i=0; i<3; i++) {
    printf("d486[%d] = %f\n", i, CPG_Result.dual->d486[i]);
  }
  for(i=0; i<3; i++) {
    printf("d487[%d] = %f\n", i, CPG_Result.dual->d487[i]);
  }
  printf("d488 = %f\n", CPG_Result.dual->d488);
  printf("d489 = %f\n", CPG_Result.dual->d489);
  printf("d490 = %f\n", CPG_Result.dual->d490);
  printf("d491 = %f\n", CPG_Result.dual->d491);
  printf("d492 = %f\n", CPG_Result.dual->d492);
  printf("d493 = %f\n", CPG_Result.dual->d493);
  printf("d494 = %f\n", CPG_Result.dual->d494);
  for(i=0; i<3; i++) {
    printf("d495[%d] = %f\n", i, CPG_Result.dual->d495[i]);
  }
  for(i=0; i<3; i++) {
    printf("d496[%d] = %f\n", i, CPG_Result.dual->d496[i]);
  }
  printf("d497 = %f\n", CPG_Result.dual->d497);
  printf("d498 = %f\n", CPG_Result.dual->d498);
  printf("d499 = %f\n", CPG_Result.dual->d499);
  printf("d500 = %f\n", CPG_Result.dual->d500);
  printf("d501 = %f\n", CPG_Result.dual->d501);
  printf("d502 = %f\n", CPG_Result.dual->d502);
  printf("d503 = %f\n", CPG_Result.dual->d503);
  for(i=0; i<3; i++) {
    printf("d504[%d] = %f\n", i, CPG_Result.dual->d504[i]);
  }
  for(i=0; i<3; i++) {
    printf("d505[%d] = %f\n", i, CPG_Result.dual->d505[i]);
  }
  printf("d506 = %f\n", CPG_Result.dual->d506);
  printf("d507 = %f\n", CPG_Result.dual->d507);
  printf("d508 = %f\n", CPG_Result.dual->d508);
  printf("d509 = %f\n", CPG_Result.dual->d509);
  printf("d510 = %f\n", CPG_Result.dual->d510);
  printf("d511 = %f\n", CPG_Result.dual->d511);
  printf("d512 = %f\n", CPG_Result.dual->d512);
  for(i=0; i<3; i++) {
    printf("d513[%d] = %f\n", i, CPG_Result.dual->d513[i]);
  }
  for(i=0; i<3; i++) {
    printf("d514[%d] = %f\n", i, CPG_Result.dual->d514[i]);
  }
  printf("d515 = %f\n", CPG_Result.dual->d515);
  printf("d516 = %f\n", CPG_Result.dual->d516);
  printf("d517 = %f\n", CPG_Result.dual->d517);
  printf("d518 = %f\n", CPG_Result.dual->d518);
  printf("d519 = %f\n", CPG_Result.dual->d519);
  printf("d520 = %f\n", CPG_Result.dual->d520);
  printf("d521 = %f\n", CPG_Result.dual->d521);
  for(i=0; i<3; i++) {
    printf("d522[%d] = %f\n", i, CPG_Result.dual->d522[i]);
  }
  for(i=0; i<3; i++) {
    printf("d523[%d] = %f\n", i, CPG_Result.dual->d523[i]);
  }
  printf("d524 = %f\n", CPG_Result.dual->d524);
  printf("d525 = %f\n", CPG_Result.dual->d525);
  printf("d526 = %f\n", CPG_Result.dual->d526);
  printf("d527 = %f\n", CPG_Result.dual->d527);
  printf("d528 = %f\n", CPG_Result.dual->d528);
  printf("d529 = %f\n", CPG_Result.dual->d529);
  printf("d530 = %f\n", CPG_Result.dual->d530);
  for(i=0; i<3; i++) {
    printf("d531[%d] = %f\n", i, CPG_Result.dual->d531[i]);
  }
  for(i=0; i<3; i++) {
    printf("d532[%d] = %f\n", i, CPG_Result.dual->d532[i]);
  }
  printf("d533 = %f\n", CPG_Result.dual->d533);
  printf("d534 = %f\n", CPG_Result.dual->d534);
  printf("d535 = %f\n", CPG_Result.dual->d535);
  printf("d536 = %f\n", CPG_Result.dual->d536);
  printf("d537 = %f\n", CPG_Result.dual->d537);
  printf("d538 = %f\n", CPG_Result.dual->d538);
  printf("d539 = %f\n", CPG_Result.dual->d539);
  printf("d540 = %f\n", CPG_Result.dual->d540);
  for(i=0; i<3; i++) {
    printf("d541[%d] = %f\n", i, CPG_Result.dual->d541[i]);
  }
  printf("d542 = %f\n", CPG_Result.dual->d542);

  return 0;

}
